# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    pictures_directory: '%kernel.project_dir%/public/uploads/pictures'
    store_logos:
        "leclerc": "images/store_logos/leclerc.png"
        "carrefour": "images/store_logos/carrefour.png"
        "auchan": "images/store_logos/auchan.png"
        "intermarche": "images/store_logos/intermarche.png"
        "casino": "images/store_logos/casino.png"
        "aldi": "images/store_logos/aldi.png"
        "lidl": "images/store_logos/lidl.png"
        "super u": "images/store_logos/super_u.png"
        "colruyt": "images/store_logos/colruyt.png"
        "monoprix": "images/store_logos/monoprix.png"
        "decathlon": "images/store_logos/decathlon.png"
        "marie blachere": "images/store_logos/marie_blachere.png"
        "ange": "images/store_logos/ange.png"
        "brico depot": "images/store_logos/brico_depot.png"
        "picard": "images/store_logos/picard.png"
        "fnac": "images/store_logos/fnac.png"
        "action": "images/store_logos/action.png"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\TicketService:
        arguments:
            $em: '@doctrine.orm.entity_manager'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
